DROP TABLE IF EXISTS post;

CREATE TABLE post (
 id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  author TEXT NOT NULL,
  message TEXT NOT NULL
);
